# Generated by Django 6.0.1 on 2026-01-16 06:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=core.models.current_time),
        ),
    ]
